
plugins:
 # - jekyll-archives # Sorry, not GitHub pages friendly!
 # - jekyll-assets
 # - autoprefixer-rails
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll/tagging
   - jekyll-tagging-related_posts

# Site settings
title: John Cammack
subtitle: Training and consultancy for non-government organisations
name: John Cammack
description: John Cammack CMS
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: ""
# the base hostname & protocol for your site
url: "https://www.johncammack.net"
logo: "/assets/logo.png"
email: "john@johncammack.net"

# Build settings
markdown: kramdown
#paginate: 5
#paginate_path: "/page:num/"
#inter_post_navigation: false
permalink: pretty
highlightjs_theme: "monokai-sublime"

# Image CDN
imagecdn:
  staging: "https://ed-johncammack-dev.imgix.net" # http://moss-chair.cloudvent.net/
  production: "https://ed-johncammack.imgix.net"

# Collections Example
collections:
    publications:
        output: true
        permalink: /publications/:path/
        #_hide_content: true


# Defaults Example
defaults:
    -
        scope:
            path: ""
        values:
            layout: "page"
    -
        scope:
            path: ""
            type: "publications"
        values:
            layout: "publication"


# Google analytics
ga_tracking_id: "UA-111283892-1"

# Google Recaptcha for contact form
recaptcha_site_key: "6LdjSh4UAAAAAKC4U7lwgH-9_hAPAoovp_j9G7zM"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets

social:
  - name: X
    icon: fa-brands fa-x-twitter
    username: 'JohnCammacknet'
    url: https://x.com/JohnCammacknet
    desc: Follow me on X
    share: true

  - name: LinkedIn
    icon: fa-brands fa-linkedin
    username: johncammack
    url: https://www.linkedin.com/in/johncammack
    desc: Connect with me on LinkedIn
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

